export default [
    {
        id : 1,
        name: "Lilly Bardenova",
        job: "Brand + Illustrator",
        role: ["Brand", "Illustrator", "Web"],
        image: "public/img1.webp",
    },
    {
        id : 2,
        name: "Victa Wille",
        job: "Digital Designer",
        role: ["Mobile", "UI", "Web"],
        image: "public/img2.webp",
    },
    {
        id : 3,
        name: "Daniele Buffa",
        job: "Pricipal Designer",
        role: ["Animation", "UI", "Visual"],
        image: "public/img3.webp",
    },
    {
        id : 4,
        name: "Elif Kamesoglu",
        job: "Brand Dsigner",
        role: ["Brand", "Illustration", "Web"],
        image: "public/img4.webp",
    },
    {
        id : 5,
        name: "Aurelien Salomon",
        job: "Design Director",
        role: ["Mobile", "Product", "UI"],
        image: "public/img5.webp",
    },
    {
        id : 6,
        name: "Chris Owens",
        job: "Creative Director",
        role: ["Illustration", "Mobile", "UI"],
        image: "public/2022-02-15-074844379.mp4",
    },
    {
        id : 7,
        name: "Vladimir Gruev",
        job: "Digital designer",
        role: ["Brand", "Design"],
        image: "public/img7.webp",
    },
    {
        id : 8,
        name: "Mercedes Bazan",
        job: "Illustration",
        role: ["Graphic Design", "Illustration"],
        image: "public/img8.webp",
    },
    {
        id : 9,
        name: "Audrea Jelic",
        job: "Digital Designer",
        role: ["Brand", "UI", "Web"],
        image: "public/img9.webp",
    }
]